version: "3.8"
services:
  postgres:
    image: "postgres:11.1-alpine"
    env_file:
      - .env_dev
    ports:
      - 5432:5432
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    env_file:
      - .env_dev
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure
  graphql-engine:
    image: hasura/graphql-engine:v2.8.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env_dev
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisor/webserver.conf", "--nodaemon" ]
    ports:
      - "80:8000"
    env_file:
      - .env_dev
    links:
      - postgres
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - graphql-engine
    volumes:
      - ./:/code
