version: "3"
services:
  postgres:
    image: "postgres:11.1-alpine"
    expose:
      - "5432"
    env_file:
      - .env_template
    volumes:
      - ../postgres-watchtower-data:/var/lib/postgresql/data
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisor/webserver.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
    env_file:
      - .env_template
    depends_on:
      - postgres
    volumes:
      - ./:/code
  redis:
    image: "redis:alpine"