version: "3"
services:
  postgres:
    image: "postgres:11.1-alpine"
    expose:
      - "5432"
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisor/webserver.conf", "--nodaemon" ]
    ports:
      - "80:8000"
    env_file:
      - .env_dev
    depends_on:
      - postgres
    volumes:
      - ./:/code
  redis:
    image: "redis:alpine"
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure
