apiVersion: v1
kind: Service
metadata:
  name: watchtower
  namespace: staging
  labels:
    app: watchtower
spec:
  selector:
    app: watchtower
  type: NodePort
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
  namespace: staging
  labels:
    app: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      containers  :
        - name: watchtower
          image: 967349720785.dkr.ecr.ap-southeast-1.amazonaws.com/watchtower-staging:842ed2488f25
          env:
            - name: POSTGRES_DB
              value: watchtower-prod
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: watchtower-redis-credentials
                  key: hostname
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: watchtower-redis-credentials
                  key: password
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: watchtower-redis-credentials
                  key: port
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: telegrambottoken
            - name: TELEGRAM_BOT_USER
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: telegrambotuser
            - name: SLACK_BOT_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: slackbotusertoken
            - name: SLACK_VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: slackverificationtoken
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: slackclientid
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: slackclientsecret
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: watchtower-credentials
                  key: slacksigningsecret
      nodeSelector:
        eks.amazonaws.com/nodegroup: watchtower-node-group
