apiVersion: v1
kind: Service
metadata:
  name: watchtower
  namespace: prod
  labels:
    app: watchtower
spec:
  selector:
    app: watchtower-webserver
  type: NodePort
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower-webserver
  namespace: prod
  labels:
    app: watchtower-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower-webserver
  template:
    metadata:
      labels:
        app: watchtower-webserver
    spec:
      containers:
        - name: watchtower-webserver
          image: registry.digitalocean.com/spicetoken/watchtower:64a226511ff4
          args: [ "supervisord", "-c", "/code/supervisor/webserver.conf", "--nodaemon" ]
          env:
            - name: DEPLOYMENT_INSTANCE
              value: prod
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: port
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: telegrambottoken
            - name: TELEGRAM_BOT_USER
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: telegrambotuser
            - name: SLACK_BOT_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: slackbotusertoken
            - name: SLACK_VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: slackverificationtoken
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: slackclientid
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: slackclientsecret
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: slacksigningsecret
